// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/rz-home-appliances-care/RzHomeAppliancesSplitHero.tsx": () => import("../components/mockups/rz-home-appliances-care/RzHomeAppliancesSplitHero.tsx")
};
